### ISSUE TITLE
Remove autoloop-extension from standard

### ISSUE THREAD

**Issue by agallou** [agallou/atoum-standard-edition#1]
For the moment, `atoum/autoloop-extension` is used in the standard edition.

But this will cause some problems : 
- the extension requires henrikbjorn/lurker. This package will not work with symfony 3 components (only on master, and, for now, there is no tag, that fixes that).

So I propose to not include the autoloop extension from the standard edition and add it in the suggested packages.

Any thoughts @jubianchi, @Grummfy ?

**Comment by Grummfy** [comment]
agree if incompatiilty

**Comment by Grummfy** [comment]
can be closed, no?
