### ISSUE TITLE
remove bootstrap file?

### ISSUE THREAD

**Issue by Grummfy** [agallou/atoum-standard-edition#6]
remove : .bootstrap.atoum.php ?
it manage the autoloader, so in the worst case => .autoloader.atoum.php , in best => no autoloader?

**Comment by agallou** [comment]
yes, with automatic include of composer autoloader (https://github.com/atoum/atoum/blob/master/CHANGELOG.md#280---2016-07-01), the boostrap is not needed anymode. I'll remove it.
